### ISSUE TITLE
Psalm 49 Verses 16 and 17...

### ISSUE THREAD

**Issue by dewhisna** [benemanuel/letteris#6]
There seems to be an issue with the column spacing in the data for Psalm 49, Verses 16 and 17:

https://github.com/benemanuel/letteris/blob/03233b590826c88a7cd482b299f5e36c780f8ca0/Psalms.utf8_txt#L751-L754

> 19O     49      15              146940  כַּצֹּ֤אן לִֽשְׁאֹ֣ול שַׁתּוּ֘ מָ֑וֶת יִ‍֫רְעֵ֥ם וַיִּרְדּוּ֘ בָ֤ם יְשָׁרִ֨ים ׀ לַבֹּ֗קֶר וְ֭ציּ֯רָם לְבַלֹּ֥ות שְׁ֜אֹ֗ול מִזְּבֻ֥ל לֹֽו׃
19O     4916            146950  אַךְ־אֱלֹהִ֗ים יִפְדֶּה־נַ֭פְשִׁי מִיַּ֣ד שְׁאֹ֑ול כִּ֖י יִקָּחֵ֣נִי סֶֽלָה׃
19O     49              17              146960  אַל־תִּ֭ירָא כִּי־יַֽעֲשִׁ֣ר אִ֑ישׁ כִּֽי־יִ֝רְבֶּ֗ה כְּבֹ֣וד בֵּיתֹֽו׃
19O     49      18              146970  כִּ֤י לֹ֣א בְּ֭מֹותֹו יִקַּ֣ח הַכֹּ֑ל לֹֽא־יֵרֵ֖ד אַֽחֲרָ֣יו כְּבֹודֹֽו׃

If you notice carefully, there's no tab character between the '49' and '16' on verse 16 and the two numbers (chapter and verse numbers) run together.  And the alignment spacing on '17' has an extra tab, making it out-of-alignment with the others.  It seems that somehow the tab from verse 16 ended on verse 17.

Somewhat minor but causes parsing issues.

**Comment by benemanuel** [comment]
fixed version23-Feb-2022
Thank you very much
